# -*- coding: utf-8 -*-

# Constants to help parse xml files

PARSER = "lxml"

UTF8 = "utf-8"

INDENT = 40

SRC_PATH = "../src/"

TPM_PATH = "tpm/"
TPM_INCLUDE_PATH = SRC_PATH + TPM_PATH + "include/"

TPM20_PREFIX_TPM2_ = "TPM2_"
TPM20_SPEC_SECTION_COMMANDS_AND_RESPONSE = "Command and Response"

# XML TAG AND ATTRIBUTE NAMES

XML_NS_TABLE = "table"
XML_NS_TEXT = "text"

XML_NS_SEPARATOR = ":"

XML_TABLE_TABLE = XML_NS_TABLE + XML_NS_SEPARATOR + "table"
XML_TABLE_NAME = XML_NS_TABLE + XML_NS_SEPARATOR + "name"
XML_TABLE_TABLE_ROW = XML_NS_TABLE + XML_NS_SEPARATOR + "table-row"
XML_TABLE_TABLE_CELL = XML_NS_TABLE + XML_NS_SEPARATOR + "table-cell"
XML_TABLE_TABLE_STYLE_NAME = XML_NS_TABLE + XML_NS_SEPARATOR + "style-name"

XML_TEXT_STYLE_NAME = XML_NS_TEXT + XML_NS_SEPARATOR + "style-name"
XML_TEXT_OUTLINE_LEVEL = XML_NS_TEXT + XML_NS_SEPARATOR + "outline-level"
XML_TEXT_LIST = XML_NS_TEXT + XML_NS_SEPARATOR + "list"
XML_TEXT_H = XML_NS_TEXT + XML_NS_SEPARATOR + "h"
XML_TEXT_P = XML_NS_TEXT + XML_NS_SEPARATOR + "p"
XML_TEXT_S = XML_NS_TEXT + XML_NS_SEPARATOR + "s"
XML_TEXT_C = XML_NS_TEXT + XML_NS_SEPARATOR + "c"
XML_TEXT_SPAN = XML_NS_TEXT + XML_NS_SEPARATOR + "span"

XML_PREFIX_CODE_ = "Code_"


# From the TCG Algorithm Registry
S_KEY_SIZES = {
    "TPM_ALG_AES": [128, 256],
    "TPM_ALG_SM4": [128],
    "TPM_ALG_CAMELLIA": [128],
}
RSA_KEY_SIZES_BITS = [1024, 2048]
ECC_CURVES = ["TPM_ECC_BN_P256", "TPM_ECC_NIST_P256", "TPM_ECC_NIST_P384"]
